title: Itnews.lat
email: ""
description: "Enfocados en las tendencias tecnológicas de los próximos años y las nuevas audiencias que están  cambiando el mercado."
author: Itnews
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
image_url: "/assets/imagenes/"
image_vzla_url: "/assets/imagenes/venezuela/"
logo_vzla: "logo-horizontal.jpg"
logo_vzla_white: "Logo-Ciberespacio-Transparente-Cuadrado.png"
logo_red: "logo_large_red.png"
logo_blue: "logo_large_blue.png"
logo_green: "logo_large_green.png"
logo_white: "logo_large_white.png"
logo_orange: "logo_large_orange.png"
logo: logo.png

# Build settings
markdown: kramdown
permalink: /:title.html

whitelist: []

collections:
  newsletters:
    output: true
    permalink: /:collection/:name

prose:
  ignore: [
    '_layouts',
    '_site',
    '_includes',
    'assets',
    '_config.yml',
    '.gitignore',
    'search.json',
    'README.MD',
    'CNAME',
    'Gemfile',
    'actualidad.html',
    'canales.html',
    'economia_digital.html',
    'feed.xml',
    'index.html',
    'movilidad.html',
    'seguridad.html',
    'transformacion_digital.html'

  ]
  siteurl: ""
  metadata:
    _newsletters:
      - name: year
        field:
          element: text
          label: Año de publicación la Notícia
          value: ""
      - name: week
        field:
          element: text
          label: Semana de publicación Notícia
          value: ""
      - name: banner
        field:
          element: text
          label: Banner para el neswlatter
          value: ""
    _posts:
      - name: layout
        field:
          element: hidden
          value: posts
      - name: color-schema
        field:
          element: text
          value: red-dark
          type: text
      - name: title
        field:
          element: text
          label: Ingrese el título de su publicación
          type: text
      - name: date
        field:
          element: text
          label: Fecha de la Publicación
          value: CURRENT_DATETIME
      - name: image
        field:
          element: text
          label: Ingrese una imagen para su publicacion
      - name: detail-image
        field:
          element: text
          label: Ingrese una imagen para el detalle de su publicación
      - name: categories
        field:
          element: multiselect
          label: Escoja el país donde estara disponible su publicación
          help: Puede escojer una o mas etiquetas
          options:
            - name: 'Todos'
              value:
                - 'Venezuela'
                - 'Colombia'
                - 'Argentina'
                - 'Perú'
                - 'Ecuador'
                - 'Chile'
                - 'Panama'
                - 'Mexico'
            - name: 'Venezuela'
              value: 'Venezuela'
            - name: 'Colombia'
              value: 'Colombia'
            - name: 'Argentina'
              value: 'Argentina'
            - name: 'Perú'
              value: 'Perú'
            - name: 'Ecuador'
              value: 'Ecuador'
            - name: 'Chile'
              value: 'Chile'
            - name: 'Panama'
              value: 'Panama'
            - name: 'México'
              value: 'Mexico'
      - name: tags
        field:
          element: multiselect
          label: Escoja o ingrese la categoría de su publicación
          help: Puede escojer una o mas etiquetas
          options:
            - name: 'Transformación Digital'
              value: 'Transformación Digital'
            - name: 'Economía Digital'
              value: 'Economía Digital'
            - name: 'Seguridad'
              value: 'Seguridad'
            - name: 'Movilidad'
              value: 'Movilidad'
            - name: 'Canales'
              value: 'Canales'
            - name: 'Actualidad'
              value: 'Actualidad'
          alterable: true
      - name: published
        field:
          element: checkbox
          label: Publicar
          help: Puede elegir entre publicar o guardar su trabajo para continuar luego.
          value: false
      - name: superNews
        field:
          element: checkbox
          label: Banner Principal
          help: Puede elegir si la publicación debe aparecer en el banner prinicipal.
          value: false
      - name: superArticle
        field:
          element: checkbox
          label: Super Noticia
          value: false
      - name: image-banner
        field:
          element: text
          label: Ingrese una imagen para el Banner prinicipal.
          value: ""
      - name: year
        field:
          element: text
          label: Año de publicación de Noticias
          value: 2018
      - name: week
        field:
          element: text
          label: Semana de publicación de Noticias
          value: ""
